version: "3.11"
services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres-service
    healthcheck:
      test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8000/health-check || exit 1
      interval: 10s
      start_period: 3s

  postgres-service:
    image: postgres:15.2-alpine
    container_name: postgres-service
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: