"""empty message

Revision ID: 6dcb4c9bf4f7
Revises: f14fa41ce13f
Create Date: 2024-01-06 12:24:25.741938

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dcb4c9bf4f7"
down_revision: Union[str, None] = "f14fa41ce13f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "products", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "user_id")
    # ### end Alembic commands ###
