"""empty message

Revision ID: b3d2ec3a497c
Revises: ab019317f863
Create Date: 2024-01-17 11:41:14.545874

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3d2ec3a497c"
down_revision: Union[str, None] = "ab019317f863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=False))
    op.add_column("users", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
